### ISSUE TITLE
EntityBuilder customization

### ISSUE THREAD

**Issue by alexonaci** [solo-io/platform-portal-backstage-plugin-backend#6]
Hi all,

We want to propose an enhancement to the EntityBuilder of this plugin. Currently the plugin fetches `customMetadata`  for each API from the Gloo Portal but it's not being mapped to a backstage API Entity field/s. Our suggestion is to implement an extension mechanism such that the plugin users could pass custom mappers to the EntityBuilder that will get applied after the current logic. If you agree with this flow (or if you have different suggestions) we would happily contribute to this effort 😄

**Comment by Charlesthebird** [comment]
Hi @alexonaci,

Thank you for your suggestion! I agree, adding some capability to map the `customMetadata` from the APIs to a Backstage Entity field would be an improvement. When you have a PR, please add me as a reviewer and I can take a look.

**Comment by Charlesthebird** [comment]
Hi @alexonaci, 

The ability to transform + extend the Backstage `Entity` before it is added to the catalog was recently added in. I documented the new steps in the "Installation" section of the Readme [here](https://github.com/solo-io/platform-portal-backstage-plugin-backend/tree/main/plugins/platform-portal-backstage-plugin-backend#installation) and published a new image (v0.0.34). I think this resolves the issue that you're describing so I will go ahead and close this.

**Comment by alexonaci** [comment]
Tested it and confirming that it fixes our issue! Thank you!!
